[General]
# Enable auto-closing logic for all doors.
bCloseDoors=1
# Allow auto-closing doors with attached scripts. Does not indicate special behavior, many regular doors have scripts attached.
bCloseDoorsWithScript=1
# Allow auto-closing any currently open door, even if it was never opened by the player or an NPC. This will close typically uncloseable doors.
bCloseDoorsWithoutPriorInteraction=0
# Delay in frames between door checks.
iTickInterval=300
# Minimum unit distance between a checked door and the player for it to be allowed to close.
fMinDistance=1000.0
# Delay in seconds until a door is allowed to be closed.
fCloseDelay=5.0